#!/usr/bin/bash

storage_dir="/storage"
snapshots_dir="/snapshots"
now=$(date +"%Y%m%d-%H%M%S")
new_snapshot="$snapshots_dir/$now"
latest_snapshot="$snapshots_dir/latest"

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: must be run as root" >&2
  exit 1
fi

if ! [[ -d "$storage_dir" ]]; then
  echo "ERROR: storage directory '$storage_dir' does not exist" >&2
  exit 1
fi

if ! [[ -d "$snapshots_dir" ]]; then
  echo "ERROR: snapshots directory '$snapshots_dir' does not exist" >&2
  exit 1
fi

if ! systemctl stop forgejo; then
  echo "ERROR: failed to stop forgejo before snapshotting" >&2
  exit 1
fi

if ! rsync -a --delete --link-dest="$latest_snapshot" "$storage_dir/" "$new_snapshot/"; then
  echo "ERROR: failed to create snapshot" >&2
  rm -rf "$new_snapshot"
  systemctl start forgejo
  exit 1
fi

if ! systemctl start forgejo; then
  echo "ERROR: failed to restart forgejo after snapshotting" >&2
  exit 1
fi

rm -f "$latest_snapshot"
ln -s "$new_snapshot" "$latest_snapshot"

echo "created new snapshot: $new_snapshot"
