#!/bin/bash
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out_dir="$repo_root/docs/pacman"
mkdir -p "$out_dir"

for host_file in "$repo_root"/hosts/*.sh; do
  host="$(basename "$host_file" .sh)"

  mapfile -t packages < <(
    (
      source "$host_file"
      for module in "${post_install_modules[@]}"; do
        f="$repo_root/modules/post-install/$module/pacman"
        [[ -f "$f" ]] && awk '!/^\s*(#|$)/ {print $1}' "$f"
      done
      printf '%s\n' "${pacman_packages[@]}"
    ) | sort -u
  )

  declare -A descs=()
  current=
  while IFS= read -r line; do
    if [[ $line =~ ^Name[[:space:]]*:[[:space:]](.+) ]]; then
      current="${BASH_REMATCH[1]}"
    elif [[ $line =~ ^Description[[:space:]]*:[[:space:]](.+) ]]; then
      descs[$current]="${BASH_REMATCH[1]}"
    fi
  done < <(pacman -Si "${packages[@]}" 2>/dev/null)

  max_len=0
  for pkg in "${packages[@]}"; do
    (( ${#pkg} > max_len )) && max_len=${#pkg}
  done

  {
    echo "# autogenerated by generate-pacman-packages.sh"
    echo
    for pkg in "${packages[@]}"; do
      printf "%-*s # %s\n" "$max_len" "$pkg" "${descs[$pkg]:-(no description)}"
    done
  } > "$out_dir/$host.md"

  echo "wrote $out_dir/$host.md"
done
